apiVersion: v2.1
kind: Deployment
metadata:
  name: myapp-deployment
  lables:
    app: myapp
    tier: frontend
spec:
  template:
    metadata:
      name: myapp-pod
      lables:
        app: myapp
        type: front-end
    spec: 
      containers:
      - name: nginx-container
        image: nginx:latest
replicas: 3
selector:
  matchlables:
    type: front-end
        
    
  
