apiVersion: v1
kind: pod
metadata: 
  name: my-pod
  labels: 
    app: my-app
    type: front-end
    env: development
spec: 
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80
      
